import type { NextConfig } from "next";

/**
 * Redirects fra det gamle WordPress-site.
 *
 * Ved migrationen til Next.js blev der ikke lagt redirects ind, så ~175 gamle
 * URLer returnerede 404, selvom de stadig rangerede i Google (ca. 3.000 visninger
 * pr. kvartal ifoelge Search Console, 2026-08-28).
 *
 * Hver kilde er verificeret til at give 404, og hvert maal til at give 200.
 * Maalene er valgt efter emne, saa placeringerne foelger med over - Google
 * behandler et irrelevant redirect som en soft-404 og smider siden ud.
 *
 * Kilder staar UDEN skraastreg til sidst: Next normaliserer "/foo/" til "/foo",
 * foer redirects matches, saa den ene form daekker begge.
 */
const legacyRedirects = [
  { source: "/1343-2", destination: "/", permanent: true },
  { source: "/education", destination: "/academy", permanent: true },
  { source: "/ai-og-affordable-business-growth-i-smver", destination: "/ai-analyse", permanent: true },
  { source: "/ai-omkostningsreduktion-danske-firmaer", destination: "/ai-analyse", permanent: true },
  { source: "/ai-vaerdi-smv", destination: "/ai-analyse", permanent: true },
  { source: "/forog-roi-med-ai-automation-i-danmark", destination: "/ai-analyse", permanent: true },
  { source: "/ai-i-inventory-management-optimering-danske-detailhandlere", destination: "/ai-i-e-commerce", permanent: true },
  { source: "/ai-optimere-lagerstyring", destination: "/ai-i-e-commerce", permanent: true },
  { source: "/ai-assistenter/medarbejderoraklet-copy", destination: "/ai-i-hr", permanent: true },
  { source: "/ai-onboarding-agenter-danmark-optimer-traening", destination: "/ai-i-hr", permanent: true },
  { source: "/ai-onboarding-agenter-danske-virksomheder", destination: "/ai-i-hr", permanent: true },
  { source: "/ai-onboarding-agenter-i-smver", destination: "/ai-i-hr", permanent: true },
  { source: "/intelligent-medarbejderhandbog", destination: "/ai-i-hr", permanent: true },
  { source: "/medarbejderhandbog-14", destination: "/ai-i-hr", permanent: true },
  { source: "/medarbejderhandbog-6", destination: "/ai-i-hr", permanent: true },
  { source: "/medarbejderhandbog-7", destination: "/ai-i-hr", permanent: true },
  { source: "/medarbejderhandbog", destination: "/ai-i-hr", permanent: true },
  { source: "/personalehandbog-14", destination: "/ai-i-hr", permanent: true },
  { source: "/personalehandbog-15", destination: "/ai-i-hr", permanent: true },
  { source: "/personalehandbog-6", destination: "/ai-i-hr", permanent: true },
  { source: "/personalehandbog-7", destination: "/ai-i-hr", permanent: true },
  { source: "/personalehandbog", destination: "/ai-i-hr", permanent: true },
  { source: "/ai-assistente-kundeservice-rolle", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistentens-rolle-i-fremtidens-smver-sadan-kommer-du-i-gang", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistenter-15", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistenter-5", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistenter-7", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistenter-dansk-kundesupport", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistenter-danske-sme", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistenter-danske-smv-2", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistenter-danske-smv-3", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistenter-danske-smv", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistenter-danske-smver-3", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistenter-danske-smver-4", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistenter-danske-smver-8", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistenter-danske-virksomheder-2", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistenter-danske-virksomheder-3", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistenter-danske-virksomheder", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistenter-fremtiden-dansk-kundeservice", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistenter-kundeservice-2", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistenter-kundeservice-3", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistenter-kundeservice-4", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistenter-kundeservice-5", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistenter-kundeservice", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistenter-kundesupport-smv", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistenter-optimerer-kundeservice", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistenter-smaa-virksomheder-2", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistenter-smaa-virksomheder", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistenter-sme-er", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistenter-smv-effektive-losninger", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistenter-til-smv", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assistents-transformation-af-kundeservice", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-assisterer-kundeforvaltning", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-automatisering-kundeservice", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-chatbot-5", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-chatbot-6", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-chatbot-integration-smaa-virksomheder", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-chatbot", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-chatbots-danish-smes", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-chatbots-for-smv", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-chatbots-forandrer-sma-danske-virksomheder", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-chatbots-kundepleje", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-chatbots-kundeservice-smv", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-chatbots-retail-revolutionerer-kundeoplevelsen", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-chatbots-sma-virksomheder-2", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-chatbots-sma-virksomheder", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-chatbots-smv-optimer-kundeservice", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-customer-support-revolution-danish-smvs", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-forbedre-kundeservice", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-forbedrer-kundeservice-2", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-forbedrer-kundeservice", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-i-kundeoplevelse-forbedring-og-besparelse", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-i-kundeservice-sma-danske-virksomheder", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-kundeadgang-i-mellemstore-virksomheder", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-kundeservice-dansk-smv-vaekst", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-kundeservice-danske-smv", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-kundeservice-smver", destination: "/ai-kundeservice", permanent: true },
  { source: "/ai-vaerktojer-kundeservice", destination: "/ai-kundeservice", permanent: true },
  { source: "/automatisering-kundesupport-ai", destination: "/ai-kundeservice", permanent: true },
  { source: "/brug-ai-assistenter-danske-virksomheder", destination: "/ai-kundeservice", permanent: true },
  { source: "/chatbot-4", destination: "/ai-kundeservice", permanent: true },
  { source: "/chatbot-5", destination: "/ai-kundeservice", permanent: true },
  { source: "/effektiv-automation-kundeservice-smver", destination: "/ai-kundeservice", permanent: true },
  { source: "/egenudviklede-ai-assistenter", destination: "/ai-kundeservice", permanent: true },
  { source: "/fordele-ai-transformer-din-kundeoplevelse", destination: "/ai-kundeservice", permanent: true },
  { source: "/fordele-ved-chatbots-for-smv-danmark", destination: "/ai-kundeservice", permanent: true },
  { source: "/forsta-ai-kundeservice", destination: "/ai-kundeservice", permanent: true },
  { source: "/fremme-kundeservice-ai-chatbots", destination: "/ai-kundeservice", permanent: true },
  { source: "/leadgeneration-chatbot", destination: "/ai-kundeservice", permanent: true },
  { source: "/optimer-kundeservice-ai-chatbots", destination: "/ai-kundeservice", permanent: true },
  { source: "/optimering-kundeservice-ai-2", destination: "/ai-kundeservice", permanent: true },
  { source: "/optimering-kundeservice-ai-3", destination: "/ai-kundeservice", permanent: true },
  { source: "/outsourcing-kundeservice-fremtidens-loesning", destination: "/ai-kundeservice", permanent: true },
  { source: "/roi-af-ai-forbedre-kundeservice", destination: "/ai-kundeservice", permanent: true },
  { source: "/undgaa-almindelige-ai-chatbot-fejl", destination: "/ai-kundeservice", permanent: true },
  { source: "/valget-af-ai-chatbot", destination: "/ai-kundeservice", permanent: true },
  { source: "/why-do-you-need-to-remember-strategy-when-working-with-ai-copy-2-copy", destination: "/ai-strategi", permanent: true },
  { source: "/why-do-you-need-to-remember-strategy-when-working-with-ai-copy-2", destination: "/ai-strategi", permanent: true },
  { source: "/why-do-you-need-to-remember-strategy-when-working-with-ai-copy", destination: "/ai-strategi", permanent: true },
  { source: "/ai-praksis-succes-cases", destination: "/cases", permanent: true },
  { source: "/se-vores-cases", destination: "/cases", permanent: true },
  { source: "/showcase-2", destination: "/cases", permanent: true },
  { source: "/showcase", destination: "/cases", permanent: true },
  { source: "/se-vores-cases/indkom", destination: "/cases/indkom-ai-partnerskab", permanent: true },
  { source: "/se-vores-cases/lavazzacase", destination: "/cases/lavazza-hr-agent", permanent: true },
  { source: "/se-vores-cases/wunderwear-kunde-case", destination: "/cases/wunderwear-automation", permanent: true },
  { source: "/cookie-policy-eu", destination: "/cookiepolitik", permanent: true },
  { source: "/terms-and-conditions", destination: "/handelsbetingelser", permanent: true },
  { source: "/kontakt-os", destination: "/kontakt", permanent: true },
  { source: "/privacy-policy", destination: "/privatlivspolitik", permanent: true },
  { source: "/ai-agenter-18", destination: "/skraeddersyede-ai", permanent: true },
  { source: "/ai-agenter-19", destination: "/skraeddersyede-ai", permanent: true },
  { source: "/ai-agenter-6", destination: "/skraeddersyede-ai", permanent: true },
  { source: "/ai-agenter-8", destination: "/skraeddersyede-ai", permanent: true },
  { source: "/ai-procesoptimering", destination: "/skraeddersyede-ai", permanent: true },
  { source: "/loesninger", destination: "/skraeddersyede-ai", permanent: true },
  { source: "/proces", destination: "/skraeddersyede-ai", permanent: true },
  { source: "/ai-knowledge", destination: "/viden-om-ai", permanent: true },
  { source: "/author/lise2024", destination: "/viden-om-ai", permanent: true },
  { source: "/blogindlaeg/page/8", destination: "/viden-om-ai", permanent: true },
  { source: "/category/hjaelptilai", destination: "/viden-om-ai", permanent: true },
  { source: "/category/hjaelptilai/page/6", destination: "/viden-om-ai", permanent: true },
  { source: "/category/hjaelptilai/page/7", destination: "/viden-om-ai", permanent: true },
  { source: "/category/uncategorized/page/2", destination: "/viden-om-ai", permanent: true },
  { source: "/optimering-smaa-virksomheder-ai", destination: "/viden-om-ai", permanent: true },
  { source: "/5-fordele-ved-ai-automationsvaerktoejer", destination: "/viden-om-ai/ai-automatisering-hvad-kan-i-automatisere", permanent: true },
  { source: "/ai-automation-fremtidens-erhverv-dk", destination: "/viden-om-ai/ai-automatisering-hvad-kan-i-automatisere", permanent: true },
  { source: "/ai-automation-fremtidens-forretningslosning", destination: "/viden-om-ai/ai-automatisering-hvad-kan-i-automatisere", permanent: true },
  { source: "/ai-automation-tools-i-smaa-virksomheder", destination: "/viden-om-ai/ai-automatisering-hvad-kan-i-automatisere", permanent: true },
  { source: "/ai-automatisering-myter-fordele-for-erhverv", destination: "/viden-om-ai/ai-automatisering-hvad-kan-i-automatisere", permanent: true },
  { source: "/ai-automatiseringsvaerktoejer-smv-danmark", destination: "/viden-om-ai/ai-automatisering-hvad-kan-i-automatisere", permanent: true },
  { source: "/ai-automatiseringsvaerktoejer-smv-produkttivitet", destination: "/viden-om-ai/ai-automatisering-hvad-kan-i-automatisere", permanent: true },
  { source: "/ai-drevne-workflows-smaa-virksomheder", destination: "/viden-om-ai/ai-automatisering-hvad-kan-i-automatisere", permanent: true },
  { source: "/ai-integration-opti-mail-automatisering", destination: "/viden-om-ai/ai-automatisering-hvad-kan-i-automatisere", permanent: true },
  { source: "/ai-powered-automation-smv", destination: "/viden-om-ai/ai-automatisering-hvad-kan-i-automatisere", permanent: true },
  { source: "/ai-vaerktoejer-danske-smv-5-fordele", destination: "/viden-om-ai/ai-automatisering-hvad-kan-i-automatisere", permanent: true },
  { source: "/ai-vaerktoejer-danske-smver", destination: "/viden-om-ai/ai-automatisering-hvad-kan-i-automatisere", permanent: true },
  { source: "/ai-vaerktoejer-rutineautomatisering", destination: "/viden-om-ai/ai-automatisering-hvad-kan-i-automatisere", permanent: true },
  { source: "/ai-vaerktoejer-sma-virksomheder", destination: "/viden-om-ai/ai-automatisering-hvad-kan-i-automatisere", permanent: true },
  { source: "/ai-vaerktojer-danske-smver", destination: "/viden-om-ai/ai-automatisering-hvad-kan-i-automatisere", permanent: true },
  { source: "/ai-vaerktojer-smaa-virksomheder", destination: "/viden-om-ai/ai-automatisering-hvad-kan-i-automatisere", permanent: true },
  { source: "/businessvaerdi-automatisering-ai-seo", destination: "/viden-om-ai/ai-automatisering-hvad-kan-i-automatisere", permanent: true },
  { source: "/effektiviser-workflow-ai", destination: "/viden-om-ai/ai-automatisering-hvad-kan-i-automatisere", permanent: true },
  { source: "/effektivisering-ai-forretning", destination: "/viden-om-ai/ai-automatisering-hvad-kan-i-automatisere", permanent: true },
  { source: "/fremtidens-ai-business-automation", destination: "/viden-om-ai/ai-automatisering-hvad-kan-i-automatisere", permanent: true },
  { source: "/optimer-forretningsprocesser-ai", destination: "/viden-om-ai/ai-automatisering-hvad-kan-i-automatisere", permanent: true },
  { source: "/praktisk-ai-effektiviser-forretningen", destination: "/viden-om-ai/ai-automatisering-hvad-kan-i-automatisere", permanent: true },
  { source: "/ai-adoption-noeglen-til-smaa-dansk-virksomheder", destination: "/viden-om-ai/ai-implementering-saadan-lykkes-det", permanent: true },
  { source: "/ai-danske-smver-implementeringer", destination: "/viden-om-ai/ai-implementering-saadan-lykkes-det", permanent: true },
  { source: "/ai-implementation-i-danske-smver", destination: "/viden-om-ai/ai-implementering-saadan-lykkes-det", permanent: true },
  { source: "/ai-integration-challenges-5-fordele", destination: "/viden-om-ai/ai-implementering-saadan-lykkes-det", permanent: true },
  { source: "/ai-mistakes-sme-undgaa-fejl", destination: "/viden-om-ai/ai-implementering-saadan-lykkes-det", permanent: true },
  { source: "/undgaa-ai-deployment-mistakes-i-danmark", destination: "/viden-om-ai/ai-implementering-saadan-lykkes-det", permanent: true },
  { source: "/undgaa-ai-implementeringsfejl", destination: "/viden-om-ai/ai-implementering-saadan-lykkes-det", permanent: true },
  { source: "/undgaa-ai-integration-fejl-danske-virksomheder", destination: "/viden-om-ai/ai-implementering-saadan-lykkes-det", permanent: true },
  { source: "/ai-danske-smver-etik", destination: "/viden-om-ai/ai-og-gdpr-saadan-bruger-i-ai-sikkert", permanent: true },
  { source: "/gdpr-ai-forsta-compliance", destination: "/viden-om-ai/ai-og-gdpr-saadan-bruger-i-ai-sikkert", permanent: true },
  { source: "/gdpr-ai-hvordan-sikre", destination: "/viden-om-ai/ai-og-gdpr-saadan-bruger-i-ai-sikkert", permanent: true },
  { source: "/gdpr-overholdelse-ai-vaerktoejer", destination: "/viden-om-ai/ai-og-gdpr-saadan-bruger-i-ai-sikkert", permanent: true },
  { source: "/virksomheder-ai-etiske-retningslinjer", destination: "/viden-om-ai/ai-og-gdpr-saadan-bruger-i-ai-sikkert", permanent: true },
  { source: "/ai-i-sales-fremtidens-salgsstrategi", destination: "/viden-om-ai/hvad-er-ai-marketing", permanent: true },
  { source: "/ai-sales-automation-roi-salgsprocesser", destination: "/viden-om-ai/hvad-er-ai-marketing", permanent: true },
  { source: "/ai-sales-tools-for-danske-smer", destination: "/viden-om-ai/hvad-er-ai-marketing", permanent: true },
  { source: "/ai-salgsstrategier-danske-smver", destination: "/viden-om-ai/hvad-er-ai-marketing", permanent: true },
  { source: "/hvordan-ai-i-salg-transformerer-danske-smv-er", destination: "/viden-om-ai/hvad-er-ai-marketing", permanent: true },
  { source: "/optimer-salg-ai-sales-strategies", destination: "/viden-om-ai/hvad-er-ai-marketing", permanent: true },
  { source: "/ai-misconceptions-aendrer-smaa-virksomheder", destination: "/viden-om-ai/hvad-er-generativ-ai", permanent: true },
  { source: "/ai-forvandler-virksomhed", destination: "/viden-om-ai/saadan-vaelger-i-jeres-foerste-ai-use-case", permanent: true },
  { source: "/ai-hverdagen-smv-danmark", destination: "/viden-om-ai/saadan-vaelger-i-jeres-foerste-ai-use-case", permanent: true },
  { source: "/ai-i-operations-smv-effektivitet", destination: "/viden-om-ai/saadan-vaelger-i-jeres-foerste-ai-use-case", permanent: true },
  { source: "/ai-produktivitet-danske-ledere", destination: "/viden-om-ai/saadan-vaelger-i-jeres-foerste-ai-use-case", permanent: true },
  { source: "/ai-smb-danmark", destination: "/viden-om-ai/saadan-vaelger-i-jeres-foerste-ai-use-case", permanent: true },
  { source: "/ai-solutions-smaa-danske-virksomheder", destination: "/viden-om-ai/saadan-vaelger-i-jeres-foerste-ai-use-case", permanent: true },
  { source: "/ai-styrke-smaa-virksomheder", destination: "/viden-om-ai/saadan-vaelger-i-jeres-foerste-ai-use-case", permanent: true },
  { source: "/effekten-af-ai-smer", destination: "/viden-om-ai/saadan-vaelger-i-jeres-foerste-ai-use-case", permanent: true },
];

const nextConfig: NextConfig = {
  // Tailwind v4's @tailwindcss/postcss bruger lightningcss som har native bindings
  // (dynamiske require af .node-filer). Next.js's bundler kan ikke statisk analysere
  // dem — eksternalisér så de loades direkte fra node_modules ved runtime.
  serverExternalPackages: ["lightningcss", "@tailwindcss/postcss", "@tailwindcss/node"],

  async redirects() {
    return legacyRedirects;
  },

  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "**.strapiapp.com",
      },
      {
        protocol: "https",
        hostname: "**.media.strapiapp.com",
      },
      {
        protocol: "http",
        hostname: "localhost",
      },
    ],
  },
};

export default nextConfig;
